In [1]:
import scipy.io
import math
import os
import glob

In [2]:
# prendi il nome di tutti i files
audio_path = "D:\\Giacomo\\Tovanella-20241110T120546Z-001\\Tovanella\\"
audio_names = os.listdir(audio_path)
audio_names[:5]

['20190601_000000.WAV',
 '20190601_010000.WAV',
 '20190601_020000.WAV',
 '20190601_030000.WAV',
 '20190601_040000.WAV']

In [3]:
import json

coords = {}
inverted_coords = {}
with open('utils\coords.json') as f:
    coords = json.load(f)
with open('utils\inverted_coords.json') as f:
    inverted_coords = json.load(f)

In [4]:
from birdnetlib.analyzer import Analyzer
from birdnetlib.batch import DirectoryAnalyzer
from pprint import pprint
from datetime import datetime
from birdnetlib import Recording

all_recordings = []
def on_analyze_complete(recording):
    print("Analyzing ", recording.path)
    all_recordings.append(recording)

def on_error(recording, error):
    print("An exception occurred: {}".format(error))
    print(recording.path)

In [ ]:
print("Starting Analyzer")
custom_model_path = "classifiers/170125_replace/CustomClassifier.tflite"
custom_labels_path = "classifiers/170125_replace/CustomClassifier_Labels.txt"

analyzer = Analyzer(
    classifier_labels_path=custom_labels_path, 
    classifier_model_path=custom_model_path,
)

all_recordings = []

print("Starting Watcher: ")
batch = DirectoryAnalyzer(
    audio_path,
    analyzers=[analyzer],
    min_conf=0.1,
)

batch.on_analyze_complete = on_analyze_complete
batch.on_error = on_error
batch.process()

# recording = Recording(
#     analyzer,
#     "d:\\Giacomo\\Tovanella-20241110T120546Z-001\\segments_2\\train\\Dryocopus martius_Black Woodpecker\\20190608_040000_3.wav",
#     min_conf=0.1,
# )
# recording.analyze()


Starting Analyzer
load_custom_models
Custom model loaded.
loading custom classifier labels
Labels loaded.
load model False
Model loaded.
Labels loaded.
load_species_list_model
Meta model loaded.
Starting Watcher: 
read_audio_data
read_audio_data: complete, read  200 chunks.
analyze_recording 20190601_000000.WAV
Analyzing  D:\Giacomo\Tovanella-20241110T120546Z-001\Tovanella\20190601_000000.WAV
read_audio_data
read_audio_data: complete, read  200 chunks.
analyze_recording 20190601_010000.WAV
Analyzing  D:\Giacomo\Tovanella-20241110T120546Z-001\Tovanella\20190601_010000.WAV
read_audio_data
read_audio_data: complete, read  200 chunks.
analyze_recording 20190601_020000.WAV
Analyzing  D:\Giacomo\Tovanella-20241110T120546Z-001\Tovanella\20190601_020000.WAV
read_audio_data
read_audio_data: complete, read  200 chunks.
analyze_recording 20190601_030000.WAV
Analyzing  D:\Giacomo\Tovanella-20241110T120546Z-001\Tovanella\20190601_030000.WAV
read_audio_data
read_audio_data: complete, read  200 chunk

In [159]:
# salva un file json con path, detections
saved_recordings = {}
for recording in all_recordings:
    saved_recordings[recording.path] = recording.as_dict

# save json file
with open('utils/detections.json', 'w') as f:
    json.dump(saved_recordings, f)

In [63]:
# crea per ogni categoria, un array di detections
# {"Wind_": [
#   [{"label": "AAAA", conf: 0.3}, {"label": "BBBB", conf: 0.3}], # segment 1
#   [{"label": "AAAA", conf: 0.3}],                               # segment 2
#   ....           
#   ]
# }
all_category_preds = {}
for recording in all_recordings:
    path = recording.as_dict["path"]
    audio = path.split("\\")[-1]
    category = path.split("\\")[-2]
    if category not in all_category_preds:
        all_category_preds[category] = []
    detections = []
    for detection in recording.detections:
        detections.append({"label": detection["label"], "conf": detection["confidence"], "audio": audio})
    all_category_preds[category].append(detections)

In [141]:
all_category_preds["Aeroplane_"]

[[{'label': 'Sylvia atricapilla_Eurasian Blackcap',
   'conf': 0.42985066771507263,
   'audio': '20190621_070000_12.wav'},
  {'label': 'Phylloscopus collybita_Common Chiffchaff',
   'conf': 0.19171887636184692,
   'audio': '20190621_070000_12.wav'},
  {'label': 'Aeroplane_',
   'conf': 0.12208954989910126,
   'audio': '20190621_070000_12.wav'},
  {'label': 'Troglodytes troglodytes_Eurasian Wren',
   'conf': 0.10442530363798141,
   'audio': '20190621_070000_12.wav'}],
 [{'label': 'Sylvia atricapilla_Eurasian Blackcap',
   'conf': 0.40162190794944763,
   'audio': '20190621_070000_13.wav'},
  {'label': 'Phylloscopus collybita_Common Chiffchaff',
   'conf': 0.18400250375270844,
   'audio': '20190621_070000_13.wav'},
  {'label': 'Aeroplane_',
   'conf': 0.12965239584445953,
   'audio': '20190621_070000_13.wav'}],
 [{'label': 'Sylvia atricapilla_Eurasian Blackcap',
   'conf': 0.46562743186950684,
   'audio': '20190621_070000_14.wav'},
  {'label': 'Aeroplane_',
   'conf': 0.32465556263923645,

# Global Evaluation
chunks are evaluated globally, there's no dependence to the original audio

In [72]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
mlb.fit([analyzer.labels])

mlb.classes_[:5]

array(['Aeroplane_', 'Certhia familiaris_Eurasian Treecreeper',
       'Dendrocopos major_Great Spotted Woodpecker',
       'Dryocopus martius_Black Woodpecker',
       'Erithacus rubecula_European Robin'], dtype=object)

In [104]:
# per ogni classe, crea la codifica binaria per i valori predetti con conf > 0.1
# in questo caso, la true label è sempre una ed è quella della cartella a cui il segmento appartiene
# percio non viene tenuto conto il caso in cui in un segmento siano presenti più labels corrette

y_true_categories = []
y_pred_categories = []

for category in all_category_preds:
    y_true = []
    y_pred = []
    for recordings in all_category_preds[category]:
        y_true_label = mlb.transform([[category]])[0]
        y_true.append(y_true_label)
        y_pred_labels = [ record["label"] for record in recordings ]
        y_pred.append(mlb.transform([y_pred_labels])[0])
        
    y_true_categories.append(y_true)
    y_pred_categories.append(y_pred)

In [127]:
all_category_preds.keys()

dict_keys(['Aeroplane_', 'Certhia familiaris_Eurasian Treecreeper', 'Dendrocopos major_Great Spotted Woodpecker', 'Dryocopus martius_Black Woodpecker', 'Erithacus rubecula_European Robin', 'Fringilla coelebs_Common Chaffinch', 'Glaucidium passerinum_Eurasian Pygmy-Owl', 'Insect_', 'Lophophanes cristatus_Crested Tit', 'Loxia curvirostra_Common Crossbill', 'Muscicapa striata_Spotted Flycatcher', 'Pecking_', 'Periparus ater_Coal Tit', 'Phylloscopus collybita_Common Chiffchaff', 'Phylloscopus trochilus_Willow Warbler', 'Pyrrhula pyrrhula_Eurasian Bullfinch', 'Rain_', 'Regulus ignicapilla_Common Firecrest', 'Regulus regulus_Goldcrest', 'Sylvia atricapilla_Eurasian Blackcap', 'Troglodytes troglodytes_Eurasian Wren', 'Turdus merula_Eurasian Blackbird', 'Turdus philomelos_Song Thrush', 'Turdus viscivorus_Mistle Thrush', 'Vegetation_', 'Wind_'])

In [148]:
import numpy as np
from sklearn.metrics import precision_recall_fscore_support

for y_true, y_pred in zip(y_true_categories, y_pred_categories):
    print(mlb.inverse_transform(np.expand_dims(y_true[0], axis=0)))
    print(precision_recall_fscore_support(y_true, y_pred, average="weighted", zero_division=0))

[('Aeroplane_',)]
(1.0, 1.0, 1.0, None)
[('Certhia familiaris_Eurasian Treecreeper',)]
(1.0, 0.2222222222222222, 0.3636363636363636, None)
[('Dendrocopos major_Great Spotted Woodpecker',)]
(0.0, 0.0, 0.0, None)
[('Dryocopus martius_Black Woodpecker',)]
(1.0, 0.2, 0.33333333333333337, None)
[('Erithacus rubecula_European Robin',)]
(1.0, 0.8888888888888888, 0.9411764705882353, None)
[('Fringilla coelebs_Common Chaffinch',)]
(1.0, 0.9413489736070382, 0.9697885196374623, None)
[('Glaucidium passerinum_Eurasian Pygmy-Owl',)]
(1.0, 0.6666666666666666, 0.8000000000000002, None)
[('Insect_',)]
(0.0, 0.0, 0.0, None)
[('Lophophanes cristatus_Crested Tit',)]
(1.0, 0.2, 0.33333333333333337, None)
[('Loxia curvirostra_Common Crossbill',)]
(1.0, 0.9565217391304348, 0.9777777777777777, None)
[('Muscicapa striata_Spotted Flycatcher',)]
(1.0, 0.9705882352941176, 0.9850746268656716, None)
[('Pecking_',)]
(1.0, 0.7142857142857143, 0.8333333333333333, None)
[('Periparus ater_Coal Tit',)]
(1.0, 0.692307692

In [134]:
from sklearn.metrics import multilabel_confusion_matrix

for y_true, y_pred in zip(y_true_categories, y_pred_categories):
    print(mlb.inverse_transform(np.expand_dims(y_true[0], axis=0)))
    print(multilabel_confusion_matrix(y_true, y_pred))

[('Aeroplane_',)]
[[[0 0]
  [0 6]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[0 6]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[0 6]
  [0 0]]

 [[4 2]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]

 [[6 0]
  [0 0]]]
[('Certhia familiaris_Eurasian Treecreeper',)]
[[[9 0]
  [0 0]]

 [[0 0]
  [7 2]]

 [[9 0]
  [0 0]]

 [[9 0]
  [0 0]]

 [[7 2]
  [0 0]]

 [[0 9]
  [0 0]]

 [[9 0]
  [0 0]]

 [[9 0]
  [0 0]]

 [[9 0]
  [0 0]]

 [[9 0]
  [0 0]]

 [[9 0]
  [0 0]]

 [[9 0]
  [0 0]]

 [[9 0]
  [0 0]]

 [[6 3]
  [0 0]]

 [[9 0]
  [0 0]]

 [[9 0]
  [0 0]]

 [[9 0]
  [0 0]]

 [[5 4]
  [0 0]]

 [[9 0]
  [0 0]]

 [[6 3]
  [0 0]]

 [[7 2]
  [0 0]]

 [[9 0]
  [0 0]]

 [[6 3]
  [0 0]]

 [[9 0]
  [0 0]]

 [[9 0]
  [0 0]]

 [[9 0]
  [0 0]]]